spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 是一个List数组，指定建表语句 //自己制定存放目录和文件名
    # schema为表初始化语句，data为数据初始化，默认加载schema.sql与data.sql。
    # 脚本位置可以通过spring.datasource.schema  与spring.datasource.data 来改变
#    schema:
#      - classpath:department.sql
    # 初始化模式（springboot2.0），其中有三个值，always为始终执行初始化，embedded只初始化内存数据库（默认值）,如h2等，never为不执行初始化
#    initialization-mode: always

    # 切换数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper

    ###################以下为druid增加的配置###########################
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      #      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 2000
      # 配置一个连接在池中最小和最大生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 600000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方,去除log4j
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      ###############################监控配置###############################
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        # 用户名和密码
        login-username: root
        login-password: root
        # ip白名单,如果allow没有配置或者为空，则允许所有访问
        allow:
        # ip黑名单,deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。
        deny: # 192.168.1.255/24
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值false
        url-pattern: /*
        # 排除一些不必要的url，比如*.js,/jslib/*等等
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # session统计功能, false：开启, true：关闭
        session-stat-enable: false
        # 缺省sessionStatMaxCount是1000个。你可以按需要进行配置
        session-stat-max-count: 1000
        # 可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
        #principal-session-name: xxx.user
        # 如果你的user信息保存在cookie中，你可以配置principalCookieName，使得druid知道当前的user是谁
        #principal-cookie-name: xxx.user
        # 配置profileEnable能够监控单个url调用的sql列表
        profile-enable: true
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #aop-patterns: com.synqnc.service.*.impl.*.(..),com.synqnc.dao.*.*.(..)